version: "3"

services:
  nginx:
    build: .
    command: ["gunicorn:8000", "1"]
    links:
      - gunicorn
    ports:
      - "8080:8000"
    environment:
      LOG: stdout
      LOG_FORMAT: '{"uri": "$$request_uri", "request_size": $$request_length}'
      LOG_FORMAT_ESCAPE: json

  gunicorn:
    build: sampleapp
